name: frontend-deploy

on:
  push:
    branches: [main] 
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:18.18.0

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: cd backend && npm install

      - name: Test
        run: cd backend && npm test

      - name: Authenticate with Google Cloud Platform
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CREDENTIALS_JSON }}
      
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'backend-spotify'
          source: '../backend'
          flags: '--allow-unauthenticated'
      
      - name: 'Use output'
        run: 'curl "${{steps.deploy.outputs.url}}"'
         